// Stub file - will be generated by Wails
export function GetAllItems() {
  return Promise.resolve([]);
}

export function GetItem(id) {
  return Promise.resolve(null);
}

export function GetItemWithAssets(id) {
  return Promise.resolve(null);
}

export function CreateItem(name, category, brand, model, serialNumber, notes) {
  return Promise.resolve(null);
}

export function UpdateItem(id, name, category, brand, model, serialNumber, notes) {
  return Promise.resolve(null);
}

export function DeleteItem(id) {
  return Promise.resolve(null);
}

export function SearchItems(query) {
  return Promise.resolve([]);
}

export function GetAssets(itemID) {
  return Promise.resolve([]);
}

export function AddAsset(itemID, assetType, name, sourcePath) {
  return Promise.resolve(null);
}

export function DeleteAsset(assetID) {
  return Promise.resolve(null);
}
