// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';
import {models} from '../models';

export function AddAsset(arg1:number,arg2:string,arg3:string,arg4:string):Promise<main.AssetDTO>;

export function CreateBackup():Promise<void>;

export function CreateItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.ItemDTO>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteItem(arg1:number):Promise<void>;

export function ExportToCSV():Promise<void>;

export function ExportToJSON():Promise<void>;

export function GenerateQRCode(arg1:number):Promise<string>;

export function GetAllItems():Promise<Array<main.ItemDTO>>;

export function GetAssets(arg1:number):Promise<Array<main.AssetDTO>>;

export function GetGossipChanges(arg1:time.Time):Promise<Array<main.ItemDTO>>;

export function GetGossipInfo():Promise<main.GossipInfoResponse>;

export function GetItem(arg1:number):Promise<main.ItemDTO>;

export function GetItemWithAssets(arg1:number):Promise<main.ItemWithAssetsDTO>;

export function GetPeers():Promise<Array<main.PeerDTO>>;

export function GetSyncHistory(arg1:number):Promise<Array<main.SyncLogDTO>>;

export function ImportFromJSON():Promise<void>;

export function RemovePeer(arg1:string):Promise<void>;

export function SearchItems(arg1:string):Promise<Array<main.ItemDTO>>;

export function SetPeerTrusted(arg1:string,arg2:boolean):Promise<void>;

export function SyncWithPeer(arg1:string):Promise<main.SyncResultDTO>;

export function SyncWithPeerHTTP(arg1:string):Promise<models.SyncResult>;

export function UpdateItem(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;
