// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAsset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAsset'](arg1, arg2, arg3, arg4);
}

export function AddPeer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPeer'](arg1, arg2, arg3);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function CreateItem(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateItem'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function ExportToCSV() {
  return window['go']['main']['App']['ExportToCSV']();
}

export function ExportToJSON() {
  return window['go']['main']['App']['ExportToJSON']();
}

export function GenerateQRCode(arg1) {
  return window['go']['main']['App']['GenerateQRCode'](arg1);
}

export function GetAllItems() {
  return window['go']['main']['App']['GetAllItems']();
}

export function GetAssets(arg1) {
  return window['go']['main']['App']['GetAssets'](arg1);
}

export function GetGossipChanges(arg1) {
  return window['go']['main']['App']['GetGossipChanges'](arg1);
}

export function GetGossipInfo() {
  return window['go']['main']['App']['GetGossipInfo']();
}

export function GetItem(arg1) {
  return window['go']['main']['App']['GetItem'](arg1);
}

export function GetItemWithAssets(arg1) {
  return window['go']['main']['App']['GetItemWithAssets'](arg1);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetSyncHistory(arg1) {
  return window['go']['main']['App']['GetSyncHistory'](arg1);
}

export function ImportFromJSON() {
  return window['go']['main']['App']['ImportFromJSON']();
}

export function RemovePeer(arg1) {
  return window['go']['main']['App']['RemovePeer'](arg1);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function SetPeerTrusted(arg1, arg2) {
  return window['go']['main']['App']['SetPeerTrusted'](arg1, arg2);
}

export function SyncWithPeer(arg1) {
  return window['go']['main']['App']['SyncWithPeer'](arg1);
}

export function SyncWithPeerHTTP(arg1) {
  return window['go']['main']['App']['SyncWithPeerHTTP'](arg1);
}

export function UpdateItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
