// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAsset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAsset'](arg1, arg2, arg3, arg4);
}

export function CreateItem(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateItem'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetAllItems() {
  return window['go']['main']['App']['GetAllItems']();
}

export function GetAssets(arg1) {
  return window['go']['main']['App']['GetAssets'](arg1);
}

export function GetItem(arg1) {
  return window['go']['main']['App']['GetItem'](arg1);
}

export function GetItemWithAssets(arg1) {
  return window['go']['main']['App']['GetItemWithAssets'](arg1);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}

export function UpdateItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
