// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"
	"time"
)

const countAssetsByItemID = `-- name: CountAssetsByItemID :one
SELECT COUNT(*) FROM assets
WHERE item_id = ?
`

func (q *Queries) CountAssetsByItemID(ctx context.Context, itemID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetsByItemID, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssetsByItemIDAndType = `-- name: CountAssetsByItemIDAndType :one
SELECT COUNT(*) FROM assets
WHERE item_id = ? AND type = ?
`

type CountAssetsByItemIDAndTypeParams struct {
	ItemID int64  `json:"item_id"`
	Type   string `json:"type"`
}

func (q *Queries) CountAssetsByItemIDAndType(ctx context.Context, arg CountAssetsByItemIDAndTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetsByItemIDAndType, arg.ItemID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    item_id, type, name, file_path, file_size, file_hash, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, item_id, type, name, file_path, file_size, file_hash, created_at
`

type CreateAssetParams struct {
	ItemID    int64     `json:"item_id"`
	Type      string    `json:"type"`
	Name      string    `json:"name"`
	FilePath  string    `json:"file_path"`
	FileSize  int64     `json:"file_size"`
	FileHash  string    `json:"file_hash"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset,
		arg.ItemID,
		arg.Type,
		arg.Name,
		arg.FilePath,
		arg.FileSize,
		arg.FileHash,
		arg.CreatedAt,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Type,
		&i.Name,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets
WHERE id = ?
`

func (q *Queries) DeleteAsset(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAsset, id)
	return err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, item_id, type, name, file_path, file_size, file_hash, created_at FROM assets
WHERE id = ?
`

func (q *Queries) GetAssetByID(ctx context.Context, id int64) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Type,
		&i.Name,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetsByItemID = `-- name: GetAssetsByItemID :many
SELECT id, item_id, type, name, file_path, file_size, file_hash, created_at FROM assets
WHERE item_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetAssetsByItemID(ctx context.Context, itemID int64) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, getAssetsByItemID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Type,
			&i.Name,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
