// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    name, category, brand, model, serial_number,
    purchase_date, photo_path, notes, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, category, brand, model, serial_number, purchase_date, photo_path, notes, created_at, updated_at
`

type CreateItemParams struct {
	Name         string       `json:"name"`
	Category     string       `json:"category"`
	Brand        string       `json:"brand"`
	Model        string       `json:"model"`
	SerialNumber string       `json:"serial_number"`
	PurchaseDate sql.NullTime `json:"purchase_date"`
	PhotoPath    string       `json:"photo_path"`
	Notes        string       `json:"notes"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Name,
		arg.Category,
		arg.Brand,
		arg.Model,
		arg.SerialNumber,
		arg.PurchaseDate,
		arg.PhotoPath,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Brand,
		&i.Model,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.PhotoPath,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, name, category, brand, model, serial_number, purchase_date, photo_path, notes, created_at, updated_at FROM items
ORDER BY updated_at DESC
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Brand,
			&i.Model,
			&i.SerialNumber,
			&i.PurchaseDate,
			&i.PhotoPath,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, category, brand, model, serial_number, purchase_date, photo_path, notes, created_at, updated_at FROM items
WHERE id = ?
`

func (q *Queries) GetItemByID(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Brand,
		&i.Model,
		&i.SerialNumber,
		&i.PurchaseDate,
		&i.PhotoPath,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchItems = `-- name: SearchItems :many
SELECT id, name, category, brand, model, serial_number, purchase_date, photo_path, notes, created_at, updated_at FROM items
WHERE name LIKE ? OR brand LIKE ? OR category LIKE ?
ORDER BY updated_at DESC
`

type SearchItemsParams struct {
	Name     string `json:"name"`
	Brand    string `json:"brand"`
	Category string `json:"category"`
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, searchItems, arg.Name, arg.Brand, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Brand,
			&i.Model,
			&i.SerialNumber,
			&i.PurchaseDate,
			&i.PhotoPath,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items
SET
    name = ?,
    category = ?,
    brand = ?,
    model = ?,
    serial_number = ?,
    purchase_date = ?,
    photo_path = ?,
    notes = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateItemParams struct {
	Name         string       `json:"name"`
	Category     string       `json:"category"`
	Brand        string       `json:"brand"`
	Model        string       `json:"model"`
	SerialNumber string       `json:"serial_number"`
	PurchaseDate sql.NullTime `json:"purchase_date"`
	PhotoPath    string       `json:"photo_path"`
	Notes        string       `json:"notes"`
	UpdatedAt    time.Time    `json:"updated_at"`
	ID           int64        `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem,
		arg.Name,
		arg.Category,
		arg.Brand,
		arg.Model,
		arg.SerialNumber,
		arg.PurchaseDate,
		arg.PhotoPath,
		arg.Notes,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
