// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID        int64     `json:"id"`
	ItemID    int64     `json:"item_id"`
	Type      string    `json:"type"`
	Name      string    `json:"name"`
	FilePath  string    `json:"file_path"`
	FileSize  int64     `json:"file_size"`
	FileHash  string    `json:"file_hash"`
	CreatedAt time.Time `json:"created_at"`
}

type Item struct {
	ID           int64        `json:"id"`
	Name         string       `json:"name"`
	Category     string       `json:"category"`
	Brand        string       `json:"brand"`
	Model        string       `json:"model"`
	SerialNumber string       `json:"serial_number"`
	PurchaseDate sql.NullTime `json:"purchase_date"`
	PhotoPath    string       `json:"photo_path"`
	Notes        string       `json:"notes"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}
