// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peers.sql

package db

import (
	"context"
	"database/sql"
)

const createPeer = `-- name: CreatePeer :one
INSERT INTO peers (id, name, address, last_seen, is_trusted)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, address, last_seen, last_sync, is_trusted, created_at
`

type CreatePeerParams struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Address   string       `json:"address"`
	LastSeen  sql.NullTime `json:"last_seen"`
	IsTrusted sql.NullBool `json:"is_trusted"`
}

func (q *Queries) CreatePeer(ctx context.Context, arg CreatePeerParams) (Peer, error) {
	row := q.db.QueryRowContext(ctx, createPeer,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.LastSeen,
		arg.IsTrusted,
	)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.LastSeen,
		&i.LastSync,
		&i.IsTrusted,
		&i.CreatedAt,
	)
	return i, err
}

const deletePeer = `-- name: DeletePeer :exec
DELETE FROM peers WHERE id = ?
`

func (q *Queries) DeletePeer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePeer, id)
	return err
}

const getAllPeers = `-- name: GetAllPeers :many
SELECT id, name, address, last_seen, last_sync, is_trusted, created_at FROM peers ORDER BY last_seen DESC
`

func (q *Queries) GetAllPeers(ctx context.Context) ([]Peer, error) {
	rows, err := q.db.QueryContext(ctx, getAllPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Peer{}
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.LastSeen,
			&i.LastSync,
			&i.IsTrusted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeer = `-- name: GetPeer :one
SELECT id, name, address, last_seen, last_sync, is_trusted, created_at FROM peers WHERE id = ?
`

func (q *Queries) GetPeer(ctx context.Context, id string) (Peer, error) {
	row := q.db.QueryRowContext(ctx, getPeer, id)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.LastSeen,
		&i.LastSync,
		&i.IsTrusted,
		&i.CreatedAt,
	)
	return i, err
}

const getPeerByAddress = `-- name: GetPeerByAddress :one
SELECT id, name, address, last_seen, last_sync, is_trusted, created_at FROM peers WHERE address = ?
`

func (q *Queries) GetPeerByAddress(ctx context.Context, address string) (Peer, error) {
	row := q.db.QueryRowContext(ctx, getPeerByAddress, address)
	var i Peer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.LastSeen,
		&i.LastSync,
		&i.IsTrusted,
		&i.CreatedAt,
	)
	return i, err
}

const getTrustedPeers = `-- name: GetTrustedPeers :many
SELECT id, name, address, last_seen, last_sync, is_trusted, created_at FROM peers WHERE is_trusted = 1 ORDER BY last_seen DESC
`

func (q *Queries) GetTrustedPeers(ctx context.Context) ([]Peer, error) {
	rows, err := q.db.QueryContext(ctx, getTrustedPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Peer{}
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.LastSeen,
			&i.LastSync,
			&i.IsTrusted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeerLastSeen = `-- name: UpdatePeerLastSeen :exec
UPDATE peers SET last_seen = ? WHERE id = ?
`

type UpdatePeerLastSeenParams struct {
	LastSeen sql.NullTime `json:"last_seen"`
	ID       string       `json:"id"`
}

func (q *Queries) UpdatePeerLastSeen(ctx context.Context, arg UpdatePeerLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updatePeerLastSeen, arg.LastSeen, arg.ID)
	return err
}

const updatePeerLastSync = `-- name: UpdatePeerLastSync :exec
UPDATE peers SET last_sync = ? WHERE id = ?
`

type UpdatePeerLastSyncParams struct {
	LastSync sql.NullTime `json:"last_sync"`
	ID       string       `json:"id"`
}

func (q *Queries) UpdatePeerLastSync(ctx context.Context, arg UpdatePeerLastSyncParams) error {
	_, err := q.db.ExecContext(ctx, updatePeerLastSync, arg.LastSync, arg.ID)
	return err
}

const updatePeerTrust = `-- name: UpdatePeerTrust :exec
UPDATE peers SET is_trusted = ? WHERE id = ?
`

type UpdatePeerTrustParams struct {
	IsTrusted sql.NullBool `json:"is_trusted"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdatePeerTrust(ctx context.Context, arg UpdatePeerTrustParams) error {
	_, err := q.db.ExecContext(ctx, updatePeerTrust, arg.IsTrusted, arg.ID)
	return err
}
