// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountAssetsByItemID(ctx context.Context, itemID int64) (int64, error)
	CountAssetsByItemIDAndType(ctx context.Context, arg CountAssetsByItemIDAndTypeParams) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	DeleteAsset(ctx context.Context, id int64) error
	DeleteItem(ctx context.Context, id int64) error
	GetAllItems(ctx context.Context) ([]Item, error)
	GetAssetByID(ctx context.Context, id int64) (Asset, error)
	GetAssetsByItemID(ctx context.Context, itemID int64) ([]Asset, error)
	GetItemByID(ctx context.Context, id int64) (Item, error)
	SearchItems(ctx context.Context, arg SearchItemsParams) ([]Item, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) error
}

var _ Querier = (*Queries)(nil)
