// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createSyncLog = `-- name: CreateSyncLog :one
INSERT INTO sync_logs (peer_id, timestamp, items_received, items_sent, conflicts, duration_ms, error)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, peer_id, timestamp, items_received, items_sent, conflicts, duration_ms, error
`

type CreateSyncLogParams struct {
	PeerID        string         `json:"peer_id"`
	Timestamp     sql.NullTime   `json:"timestamp"`
	ItemsReceived sql.NullInt64  `json:"items_received"`
	ItemsSent     sql.NullInt64  `json:"items_sent"`
	Conflicts     sql.NullInt64  `json:"conflicts"`
	DurationMs    sql.NullInt64  `json:"duration_ms"`
	Error         sql.NullString `json:"error"`
}

func (q *Queries) CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRowContext(ctx, createSyncLog,
		arg.PeerID,
		arg.Timestamp,
		arg.ItemsReceived,
		arg.ItemsSent,
		arg.Conflicts,
		arg.DurationMs,
		arg.Error,
	)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.PeerID,
		&i.Timestamp,
		&i.ItemsReceived,
		&i.ItemsSent,
		&i.Conflicts,
		&i.DurationMs,
		&i.Error,
	)
	return i, err
}

const deleteOldSyncLogs = `-- name: DeleteOldSyncLogs :exec
DELETE FROM sync_logs WHERE timestamp < ?
`

func (q *Queries) DeleteOldSyncLogs(ctx context.Context, timestamp sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteOldSyncLogs, timestamp)
	return err
}

const getRecentSyncLogs = `-- name: GetRecentSyncLogs :many
SELECT id, peer_id, timestamp, items_received, items_sent, conflicts, duration_ms, error FROM sync_logs ORDER BY timestamp DESC LIMIT ?
`

func (q *Queries) GetRecentSyncLogs(ctx context.Context, limit int64) ([]SyncLog, error) {
	rows, err := q.db.QueryContext(ctx, getRecentSyncLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncLog{}
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.PeerID,
			&i.Timestamp,
			&i.ItemsReceived,
			&i.ItemsSent,
			&i.Conflicts,
			&i.DurationMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncLog = `-- name: GetSyncLog :one
SELECT id, peer_id, timestamp, items_received, items_sent, conflicts, duration_ms, error FROM sync_logs WHERE id = ?
`

func (q *Queries) GetSyncLog(ctx context.Context, id int64) (SyncLog, error) {
	row := q.db.QueryRowContext(ctx, getSyncLog, id)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.PeerID,
		&i.Timestamp,
		&i.ItemsReceived,
		&i.ItemsSent,
		&i.Conflicts,
		&i.DurationMs,
		&i.Error,
	)
	return i, err
}

const getSyncLogsByPeer = `-- name: GetSyncLogsByPeer :many
SELECT id, peer_id, timestamp, items_received, items_sent, conflicts, duration_ms, error FROM sync_logs WHERE peer_id = ? ORDER BY timestamp DESC LIMIT ?
`

type GetSyncLogsByPeerParams struct {
	PeerID string `json:"peer_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) GetSyncLogsByPeer(ctx context.Context, arg GetSyncLogsByPeerParams) ([]SyncLog, error) {
	rows, err := q.db.QueryContext(ctx, getSyncLogsByPeer, arg.PeerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncLog{}
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.PeerID,
			&i.Timestamp,
			&i.ItemsReceived,
			&i.ItemsSent,
			&i.Conflicts,
			&i.DurationMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
